insert into animal values(1, 'Lion', 1);
insert into animal values(2, 'Tiger',  1);
insert into animal values(3,  'Chitah', 1);
insert into animal values(4, 'Ostrich', 4);
insert into animal values(5, 'Duck',  3);
insert into animal values(6,  'Emu',3);
insert into animal values(7, 'Gese', 4);
insert into animal values(16, 'Pegion', 3);
insert into animal values(8, 'Polar bear',  1);
insert into animal values(9,  'Wolf', 1);
insert into animal values(10, 'Cayoties', 1);
insert into animal values(11, 'Brown bear',  1);
insert into animal values(12,  'Black bear', 1);
insert into animal values(13, 'Monkey', 1);
insert into animal values(14, 'Snake',  2);
insert into animal values(15,  'Alegator', 2);